### ISSUE TITLE
Error occurred when compile on macOS Big Sur 11.7.10

### ISSUE THREAD

**Issue by Ashearan** [domcyrus/rustnet#13]
note: Undefined symbols for architecture x86_64:
            "_pcap_set_want_pktap", referenced from:
                pcap::capture::inactive::_$LT$impl$u20$pcap..capture..Capture$LT$pcap..capture..Inactive$GT$$GT$::want_pktap::h20cd9b25ce423f37 in libpcap-03074675de5926dc.rlib(pcap-03074675de5926dc.pcap.52e9c4420994b087-cgu.1.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

Installed libpcap from port:
port installed | grep libpcap                                                                   
libpcap @1.10.5_0 (active)

**Comment by domcyrus** [comment]
Thanks @Ashearan for creating this issue. I believe this could be related to the way `RustNet` depends on macOS systems pcap version which provides pktab functionality but the version you get via MacPorts may not.

Could you try this:
```sh
sudo port deactivate libpcap

# Clean and rebuild
cargo clean
cargo build --release
```

**Comment by Ashearan** [comment]
`sudo port deactivate libpcap` did like a charm.

Compilation was successful. Thank you very much.
